### ISSUE TITLE
How to specify path for t2?

### ISSUE THREAD

**Issue by soichih** [pegasus-isi/freesurfer-osg-workflow#6]
I am trying to figure out how to set  `-hippocampal-subfields-T1T2` option for autorecon-options in run.yml. This option requires path to the T2 file if specified.

Currently, I have the following script to customize the command line option based on user input.

```
cmd="-i $t1 -subject output -all -parallel -openmp $OMP_NUM_THREADS"
if [ -f $t2 ]; then
    cmd="$cmd -T2 $t2 -T2pial"
    #https://surfer.nmr.mgh.harvard.edu/fswiki/HippocampalSubfields
    #https://surfer.nmr.mgh.harvard.edu/fswiki/HippocampalSubfieldsAndNucleiOfAmygdala
    if [ $hippocampal == "true" ]; then
        cmd="$cmd -hippocampal-subfields-T1T2 $t2 t1t2"
    fi
else
    if [ $hippocampal == "true" ]; then
        cmd="$cmd -hippocampal-subfields-T1"
    fi
fi
```

Since I can't just use the local path for T2 in autorecon-options (right?) I am not sure how to go about specifying this option. Is it possible to set this option?

**Comment by soichih** [comment]
By the way, I have something like this in the run.yml

```
subject:
    input: ../5ea9b9004623da2e63eddf98/5e73d1040b1be19b0f341eec/t1.nii.gz
    T2: ../5ea9b9004623da2e63eddf98/5e73d1040b1be19b0f341eec/t2.nii.gz
    autorecon-options: -notal-check -cw256
```

I just don't know how to specify -hippocampal-subfields-T1T2 option for the autorecon-options.

**Comment by soichih** [comment]
Actually, I just learned that `hippocampal-subfields` options are replaced by completely separate scripts that I have to run after recon-all is completed (for freesurfer v7)

```
segmentHA_T1.sh  (if user only has t1)
segmentHA_T2.sh  (if user has both t1 and t2)
```

Is it possible to add a step after recon-all to run one of these commands? I think this actually make it easier to handle hoppocampal-subfields option as I don't have to worry about T2 path anymore.

**Comment by rynge** [comment]
Sure - how would you like to specify that option? How about:

```
subject:
    input: ../5ea9b9004623da2e63eddf98/5e73d1040b1be19b0f341eec/t1.nii.gz
    T2: ../5ea9b9004623da2e63eddf98/5e73d1040b1be19b0f341eec/t2.nii.gz
    autorecon-options: -notal-check -cw256
    hippocampal-subfields: True
```
